==== START logs for container kube-proxy of pod kube-system/kube-proxy-6lln4 ====
W0510 23:05:47.785313       1 server_others.go:324] Unknown proxy mode "", assuming iptables proxy
I0510 23:05:47.793910       1 node.go:135] Successfully retrieved node IP: 172.17.0.4
I0510 23:05:47.794009       1 server_others.go:145] Using iptables Proxier.
I0510 23:05:47.794630       1 server.go:571] Version: v1.17.5
I0510 23:05:47.795052       1 conntrack.go:52] Setting nf_conntrack_max to 196608
I0510 23:05:47.795970       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0510 23:05:47.796036       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0510 23:05:47.796513       1 config.go:131] Starting endpoints config controller
I0510 23:05:47.796539       1 config.go:313] Starting service config controller
I0510 23:05:47.796550       1 shared_informer.go:197] Waiting for caches to sync for service config
I0510 23:05:47.796553       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
I0510 23:05:47.897603       1 shared_informer.go:204] Caches are synced for service config 
I0510 23:05:47.897618       1 shared_informer.go:204] Caches are synced for endpoints config 
I0510 23:06:19.983718       1 trace.go:116] Trace[945095608]: "iptables restore" (started: 2021-05-10 23:06:17.902869297 +0000 UTC m=+30.338956607) (total time: 2.080817533s):
Trace[945095608]: [2.080817533s] [2.080817533s] END
E0510 23:11:29.228182       1 proxier.go:787] Failed to ensure that filter chain KUBE-FORWARD exists: error creating chain "KUBE-FORWARD": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
I0510 23:11:29.228266       1 proxier.go:779] Sync failed; retrying in 30s
E0510 23:11:34.237109       1 proxier.go:787] Failed to ensure that filter chain KUBE-EXTERNAL-SERVICES exists: error creating chain "KUBE-EXTERNAL-SERVICES": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
I0510 23:11:34.237150       1 proxier.go:779] Sync failed; retrying in 30s
I0510 23:11:51.944206       1 trace.go:116] Trace[1471437868]: "iptables restore" (started: 2021-05-10 23:11:49.489504514 +0000 UTC m=+362.159689310) (total time: 2.45463548s):
Trace[1471437868]: [2.45463548s] [2.45463548s] END
I0510 23:12:02.821295       1 trace.go:116] Trace[780633078]: "iptables restore" (started: 2021-05-10 23:12:00.466502769 +0000 UTC m=+373.158270043) (total time: 2.354756906s):
Trace[780633078]: [2.354756906s] [2.354756906s] END
I0510 23:12:23.167351       1 trace.go:116] Trace[1774787375]: "iptables restore" (started: 2021-05-10 23:12:20.515214196 +0000 UTC m=+393.206981437) (total time: 2.652035258s):
Trace[1774787375]: [2.652035258s] [2.652035258s] END
I0510 23:18:25.786290       1 trace.go:116] Trace[1524478817]: "iptables restore" (started: 2021-05-10 23:18:23.661760732 +0000 UTC m=+756.625684198) (total time: 2.121203338s):
Trace[1524478817]: [2.121203338s] [2.121203338s] END
I0510 23:18:33.640867       1 trace.go:116] Trace[289828118]: "iptables save" (started: 2021-05-10 23:18:31.594322586 +0000 UTC m=+764.558246056) (total time: 2.046485397s):
Trace[289828118]: [2.046485397s] [2.046485397s] END
I0510 23:18:35.761354       1 trace.go:116] Trace[2140990759]: "iptables restore" (started: 2021-05-10 23:18:33.642164262 +0000 UTC m=+766.606087751) (total time: 2.119125413s):
Trace[2140990759]: [2.119125413s] [2.119125413s] END
==== END logs for container kube-proxy of pod kube-system/kube-proxy-6lln4 ====
