LOGS TOTAL
        23

ERRORS TOTAL
  192

ERRORS COUNT

  72 ./config.kubeconfig/nsm-system/nsmgr-cloudtest-kind-8a1853245b-worker/logs.txt
  34 ./config.kubeconfig/nsm-system/nsmd-forwarder-cloudtest-kind-8a1853245b-worker/logs.txt
  17 ./config.kubeconfig/nsm-system/icmp-responder-nse-3/logs.txt
  17 ./config.kubeconfig/nsm-system/icmp-responder-nse-2/logs.txt
  9 ./config.kubeconfig/spire/spire-agent-vp6pj/logs.txt
  9 ./config.kubeconfig/spire/spire-agent-t72wk/logs.txt
  8 ./config.kubeconfig/spire/spire-server-0/logs.txt
  8 ./config.kubeconfig/spire/spire-agent-vc6zj/logs.txt
  5 ./config.kubeconfig/local-path-storage/local-path-provisioner-7745554f7f-6g5d7/logs.txt
  3 ./config.kubeconfig/kube-system/kube-controller-manager-cloudtest-kind-8a1853245b-control-plane/logs.txt
  3 ./config.kubeconfig/kube-system/kube-apiserver-cloudtest-kind-8a1853245b-control-plane/logs.txt
  2 ./config.kubeconfig/nsm-system/spire-proxy/logs.txt
  1 ./config.kubeconfig/kube-system/kube-scheduler-cloudtest-kind-8a1853245b-control-plane/logs.txt
  1 ./config.kubeconfig/kube-system/kindnet-sk257/logs.txt
  1 ./config.kubeconfig/kube-system/kindnet-gnvzd/logs.txt
  1 ./config.kubeconfig/kube-system/kindnet-c6rs2/logs.txt
  1 ./config.kubeconfig/kube-system/etcd-cloudtest-kind-8a1853245b-control-plane/logs.txt

ERRORS OCCURENCES

  ./config.kubeconfig/nsm-system/icmp-responder-nse-3/logs.txt
  
  	86:INFO: 2021/06/11 16:43:27 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	94:INFO: 2021/06/11 16:43:27 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	156:INFO: 2021/06/11 16:43:27 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	160:INFO: 2021/06/11 16:43:28 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	163:INFO: 2021/06/11 16:43:28 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	167:WARNING: 2021/06/11 16:43:28 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	169:INFO: 2021/06/11 16:43:28 [core] pickfirstBalancer: UpdateSubConnState: 0xc000448060, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	175:WARNING: 2021/06/11 16:43:29 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	177:INFO: 2021/06/11 16:43:29 [core] pickfirstBalancer: UpdateSubConnState: 0xc000448060, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	183:WARNING: 2021/06/11 16:43:31 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	185:INFO: 2021/06/11 16:43:31 [core] pickfirstBalancer: UpdateSubConnState: 0xc000448060, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	189:WARNING: 2021/06/11 16:43:33 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	193:INFO: 2021/06/11 16:43:33 [core] pickfirstBalancer: UpdateSubConnState: 0xc000448060, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	199:WARNING: 2021/06/11 16:43:38 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	201:INFO: 2021/06/11 16:43:38 [core] pickfirstBalancer: UpdateSubConnState: 0xc000448060, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	205:WARNING: 2021/06/11 16:43:43 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	209:INFO: 2021/06/11 16:43:43 [core] pickfirstBalancer: UpdateSubConnState: 0xc000448060, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  
  
  ./config.kubeconfig/nsm-system/icmp-responder-nse-2/logs.txt
  
  	77:INFO: 2021/06/11 16:43:23 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	103:INFO: 2021/06/11 16:43:23 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	157:INFO: 2021/06/11 16:43:23 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	161:INFO: 2021/06/11 16:43:28 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	165:WARNING: 2021/06/11 16:43:28 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	167:INFO: 2021/06/11 16:43:28 [core] pickfirstBalancer: UpdateSubConnState: 0xc00038a530, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	171:INFO: 2021/06/11 16:43:28 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	176:WARNING: 2021/06/11 16:43:29 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	178:INFO: 2021/06/11 16:43:29 [core] pickfirstBalancer: UpdateSubConnState: 0xc00038a530, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	182:WARNING: 2021/06/11 16:43:30 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	186:INFO: 2021/06/11 16:43:30 [core] pickfirstBalancer: UpdateSubConnState: 0xc00038a530, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	190:WARNING: 2021/06/11 16:43:33 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	194:INFO: 2021/06/11 16:43:33 [core] pickfirstBalancer: UpdateSubConnState: 0xc00038a530, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	200:WARNING: 2021/06/11 16:43:37 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	202:INFO: 2021/06/11 16:43:37 [core] pickfirstBalancer: UpdateSubConnState: 0xc00038a530, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  	208:WARNING: 2021/06/11 16:43:44 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.server.io.sock /var/lib/networkservicemesh/nsm.server.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused". Reconnecting...
  	210:INFO: 2021/06/11 16:43:44 [core] pickfirstBalancer: UpdateSubConnState: 0xc00038a530, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.server.io.sock: connect: connection refused"}
  
  
  ./config.kubeconfig/nsm-system/nsmd-forwarder-cloudtest-kind-8a1853245b-worker/logs.txt
  
  	477:time="2021-06-11 16:43:01.86451" level=warning msg="grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 127.0.0.1:9111->127.0.0.1:42210: read: connection reset by peer\"" loc="grpclog/grpclog.go(42)" logger=grpc.grpc-server
  	558:time="2021-06-11 16:43:02.02266" level=warning msg="grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams failed to receive the preface from client: EOF\"" loc="grpclog/grpclog.go(42)" logger=grpc.grpc-server
  	564:INFO: 2021/06/11 16:43:02 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	667:INFO: 2021/06/11 16:43:02 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	737:INFO: 2021/06/11 16:43:12 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	764:INFO: 2021/06/11 16:43:12 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	780:INFO: 2021/06/11 16:43:12 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	781:INFO: 2021/06/11 16:43:12 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	849:time="2021-06-11T16:43:28Z" level=error msg="vppagent: fail to receive from liveness grpc channel with error: rpc error: code = Unavailable desc = error reading from server: EOF, grpc code: Unavailable"
  	856:WARNING: 2021/06/11 16:43:28 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	858:INFO: 2021/06/11 16:43:28 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	860:INFO: 2021/06/11 16:43:28 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	863:INFO: 2021/06/11 16:43:28 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	864:INFO: 2021/06/11 16:43:28 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	867:WARNING: 2021/06/11 16:43:29 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	871:INFO: 2021/06/11 16:43:29 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	897:WARNING: 2021/06/11 16:43:31 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	899:INFO: 2021/06/11 16:43:31 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	903:WARNING: 2021/06/11 16:43:33 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	907:INFO: 2021/06/11 16:43:33 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	913:WARNING: 2021/06/11 16:43:38 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	915:INFO: 2021/06/11 16:43:38 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	939:WARNING: 2021/06/11 16:43:45 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	943:INFO: 2021/06/11 16:43:45 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	969:WARNING: 2021/06/11 16:43:56 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	971:INFO: 2021/06/11 16:43:56 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	977:WARNING: 2021/06/11 16:44:13 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	979:INFO: 2021/06/11 16:44:13 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	984:WARNING: 2021/06/11 16:44:41 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	988:INFO: 2021/06/11 16:44:41 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	993:WARNING: 2021/06/11 16:45:31 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	997:INFO: 2021/06/11 16:45:31 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  	1004:WARNING: 2021/06/11 16:46:42 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory". Reconnecting...
  	1006:INFO: 2021/06/11 16:46:42 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002a4200, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm.forwarder-registrar.io.sock: connect: no such file or directory"}
  
  
  ./config.kubeconfig/nsm-system/spire-proxy/logs.txt
  
  	94:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	95:time="2021-06-11T16:43:51Z" level=error msg="rpc error: code = Canceled desc = context canceled"
  
  
  ./config.kubeconfig/nsm-system/nsmgr-cloudtest-kind-8a1853245b-worker/logs.txt
  
  	70:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	74:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	96:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	134:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	153:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	167:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	210:INFO: 2021/06/11 16:44:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	220:INFO: 2021/06/11 16:44:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	249:INFO: 2021/06/11 16:44:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	274:INFO: 2021/06/11 16:44:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	292:INFO: 2021/06/11 16:44:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	317:INFO: 2021/06/11 16:44:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	358:INFO: 2021/06/11 16:45:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	365:INFO: 2021/06/11 16:45:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	391:INFO: 2021/06/11 16:45:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	425:INFO: 2021/06/11 16:45:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	438:INFO: 2021/06/11 16:45:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	461:INFO: 2021/06/11 16:45:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	502:INFO: 2021/06/11 16:46:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	512:INFO: 2021/06/11 16:46:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	541:INFO: 2021/06/11 16:46:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	570:INFO: 2021/06/11 16:46:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	584:INFO: 2021/06/11 16:46:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	608:INFO: 2021/06/11 16:46:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	718:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	739:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	785:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	804:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	815:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	824:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	825:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	916:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	932:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	943:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	950:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	952:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	993:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1032:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1046:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1057:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1069:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1073:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1144:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1158:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1166:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1178:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1183:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1208:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1216:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1226:WARNING: 2021/06/11 16:43:51 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm-12/nsm.client.io.sock /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory". Reconnecting...
  	1228:INFO: 2021/06/11 16:43:51 [core] pickfirstBalancer: UpdateSubConnState: 0xc0004d4ea0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory"}
  	1234:WARNING: 2021/06/11 16:43:52 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm-12/nsm.client.io.sock /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory". Reconnecting...
  	1236:INFO: 2021/06/11 16:43:52 [core] pickfirstBalancer: UpdateSubConnState: 0xc0004d4ea0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory"}
  	1240:WARNING: 2021/06/11 16:43:53 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm-12/nsm.client.io.sock /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory". Reconnecting...
  	1244:INFO: 2021/06/11 16:43:53 [core] pickfirstBalancer: UpdateSubConnState: 0xc0004d4ea0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory"}
  	1248:WARNING: 2021/06/11 16:43:56 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm-12/nsm.client.io.sock /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory". Reconnecting...
  	1252:INFO: 2021/06/11 16:43:56 [core] pickfirstBalancer: UpdateSubConnState: 0xc0004d4ea0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory"}
  	1256:WARNING: 2021/06/11 16:44:00 [core] grpc: addrConn.createTransport failed to connect to {/var/lib/networkservicemesh/nsm-12/nsm.client.io.sock /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory". Reconnecting...
  	1260:INFO: 2021/06/11 16:44:00 [core] pickfirstBalancer: UpdateSubConnState: 0xc0004d4ea0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /var/lib/networkservicemesh/nsm-12/nsm.client.io.sock: connect: no such file or directory"}
  	1264:INFO: 2021/06/11 16:44:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1269:INFO: 2021/06/11 16:44:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1270:INFO: 2021/06/11 16:44:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1275:INFO: 2021/06/11 16:44:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1276:INFO: 2021/06/11 16:45:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1281:INFO: 2021/06/11 16:45:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1282:INFO: 2021/06/11 16:45:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1287:INFO: 2021/06/11 16:45:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1288:INFO: 2021/06/11 16:46:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1293:INFO: 2021/06/11 16:46:21 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1294:INFO: 2021/06/11 16:46:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1299:INFO: 2021/06/11 16:46:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  	1392:INFO: 2021/06/11 16:43:51 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
  
  
  ./config.kubeconfig/local-path-storage/local-path-provisioner-7745554f7f-6g5d7/logs.txt
  
  	4:ERROR: logging before flag.Parse: I0611 16:35:58.627493       1 leaderelection.go:187] attempting to acquire leader lease  local-path-storage/rancher.io-local-path...
  	5:ERROR: logging before flag.Parse: I0611 16:35:58.660415       1 leaderelection.go:196] successfully acquired lease local-path-storage/rancher.io-local-path
  	6:ERROR: logging before flag.Parse: I0611 16:35:58.662307       1 controller.go:572] Starting provisioner controller rancher.io/local-path_local-path-provisioner-7745554f7f-6g5d7_19e4d51f-cad3-11eb-87c2-62ba0426e9d5!
  	7:ERROR: logging before flag.Parse: I0611 16:35:58.663384       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"local-path-storage", Name:"rancher.io-local-path", UID:"6f32690d-f018-4c04-822e-7ce85f7c77e7", APIVersion:"v1", ResourceVersion:"641", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' local-path-provisioner-7745554f7f-6g5d7_19e4d51f-cad3-11eb-87c2-62ba0426e9d5 became leader
  	8:ERROR: logging before flag.Parse: I0611 16:35:58.775166       1 controller.go:621] Started provisioner controller rancher.io/local-path_local-path-provisioner-7745554f7f-6g5d7_19e4d51f-cad3-11eb-87c2-62ba0426e9d5!
  
  
  ./config.kubeconfig/spire/spire-agent-t72wk/logs.txt
  
  	67:time="2021-06-11T16:38:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	307:time="2021-06-11T16:39:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	314:time="2021-06-11T16:40:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	319:time="2021-06-11T16:41:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	323:time="2021-06-11T16:42:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	687:time="2021-06-11T16:43:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	699:time="2021-06-11T16:44:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	711:time="2021-06-11T16:45:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	723:time="2021-06-11T16:46:55Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  
  
  ./config.kubeconfig/spire/spire-agent-vc6zj/logs.txt
  
  	44:time="2021-06-11T16:39:43Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	48:time="2021-06-11T16:40:43Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	52:time="2021-06-11T16:41:43Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	56:time="2021-06-11T16:42:43Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	60:time="2021-06-11T16:43:42Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	64:time="2021-06-11T16:44:42Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	68:time="2021-06-11T16:45:42Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	72:time="2021-06-11T16:46:42Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  
  
  ./config.kubeconfig/spire/spire-agent-vp6pj/logs.txt
  
  	44:time="2021-06-11T16:38:48Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	48:time="2021-06-11T16:39:47Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	52:time="2021-06-11T16:40:47Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	56:time="2021-06-11T16:41:47Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	60:time="2021-06-11T16:42:47Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	64:time="2021-06-11T16:43:47Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	68:time="2021-06-11T16:44:47Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	72:time="2021-06-11T16:45:47Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  	76:time="2021-06-11T16:46:47Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
  
  
  ./config.kubeconfig/spire/spire-server-0/logs.txt
  
  	11:WARNING: 2021/06/11 16:38:05 [core] grpc: addrConn.createTransport failed to connect to {/run/spire/sockets/registration.sock /run/spire/sockets/registration.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /run/spire/sockets/registration.sock: connect: no such file or directory". Reconnecting...
  	15:INFO: 2021/06/11 16:38:05 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001bcd10, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /run/spire/sockets/registration.sock: connect: no such file or directory"}
  	21:WARNING: 2021/06/11 16:38:06 [core] grpc: addrConn.createTransport failed to connect to {/run/spire/sockets/registration.sock /run/spire/sockets/registration.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /run/spire/sockets/registration.sock: connect: no such file or directory". Reconnecting...
  	23:INFO: 2021/06/11 16:38:06 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001bcd10, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /run/spire/sockets/registration.sock: connect: no such file or directory"}
  	27:WARNING: 2021/06/11 16:38:07 [core] grpc: addrConn.createTransport failed to connect to {/run/spire/sockets/registration.sock /run/spire/sockets/registration.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /run/spire/sockets/registration.sock: connect: no such file or directory". Reconnecting...
  	31:INFO: 2021/06/11 16:38:07 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001bcd10, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /run/spire/sockets/registration.sock: connect: no such file or directory"}
  	35:WARNING: 2021/06/11 16:38:10 [core] grpc: addrConn.createTransport failed to connect to {/run/spire/sockets/registration.sock /run/spire/sockets/registration.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /run/spire/sockets/registration.sock: connect: no such file or directory". Reconnecting...
  	39:INFO: 2021/06/11 16:38:10 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001bcd10, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial unix /run/spire/sockets/registration.sock: connect: no such file or directory"}
  
  
  ./config.kubeconfig/kube-system/kube-apiserver-cloudtest-kind-8a1853245b-control-plane/logs.txt
  
  	232:E0611 16:39:21.097323       1 upgradeaware.go:357] Error proxying data from client to backend: write tcp 172.17.0.3:60634->172.17.0.2:10250: write: connection reset by peer
  	235:E0611 16:39:28.707988       1 upgradeaware.go:371] Error proxying data from backend to client: tls: use of closed connection
  	242:E0611 16:42:33.414397       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
  
  
  ./config.kubeconfig/kube-system/kindnet-sk257/logs.txt
  
  	4:I0611 16:36:13.845338       1 main.go:104] Failed to get nodes, retrying after error: Get https://10.96.0.1:443/api/v1/nodes: dial tcp 10.96.0.1:443: i/o timeout
  
  
  ./config.kubeconfig/kube-system/kube-scheduler-cloudtest-kind-8a1853245b-control-plane/logs.txt
  
  	6:W0611 16:34:53.174204       1 authentication.go:296] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:kube-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
  
  
  ./config.kubeconfig/kube-system/kindnet-c6rs2/logs.txt
  
  	4:I0611 16:35:50.276294       1 main.go:104] Failed to get nodes, retrying after error: Get https://10.96.0.1:443/api/v1/nodes: dial tcp 10.96.0.1:443: i/o timeout
  
  
  ./config.kubeconfig/kube-system/kube-controller-manager-cloudtest-kind-8a1853245b-control-plane/logs.txt
  
  	10:E0611 16:34:53.164552       1 leaderelection.go:331] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
  	200:E0611 16:35:38.822341       1 daemon_controller.go:290] kube-system/kube-proxy failed with : error storing status for daemon set &v1.DaemonSet{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-proxy", GenerateName:"", Namespace:"kube-system", SelfLink:"/apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy", UID:"302a5b80-e8cc-4b4e-8cd4-936352209d1d", ResourceVersion:"524", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63759026096, loc:(*time.Location)(0x3992980)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"k8s-app":"kube-proxy"}, Annotations:map[string]string{"deprecated.daemonset.template.generation":"1"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1.DaemonSetSpec{Selector:(*v1.LabelSelector)(0xc001d2d2c0), Template:v1.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"k8s-app":"kube-proxy"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1.PodSpec{Volumes:[]v1.Volume{v1.Volume{Name:"kube-proxy", VolumeSource:v1.VolumeSource{HostPath:(*v1.HostPathVolumeSource)(nil), EmptyDir:(*v1.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*v1.GitRepoVolumeSource)(nil), Secret:(*v1.SecretVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), ISCSI:(*v1.ISCSIVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*v1.PersistentVolumeClaimVolumeSource)(nil), RBD:(*v1.RBDVolumeSource)(nil), FlexVolume:(*v1.FlexVolumeSource)(nil), Cinder:(*v1.CinderVolumeSource)(nil), CephFS:(*v1.CephFSVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), DownwardAPI:(*v1.DownwardAPIVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), AzureFile:(*v1.AzureFileVolumeSource)(nil), ConfigMap:(*v1.ConfigMapVolumeSource)(0xc001d20800), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), Projected:(*v1.ProjectedVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOVolumeSource)(nil), StorageOS:(*v1.StorageOSVolumeSource)(nil), CSI:(*v1.CSIVolumeSource)(nil)}}, v1.Volume{Name:"xtables-lock", VolumeSource:v1.VolumeSource{HostPath:(*v1.HostPathVolumeSource)(0xc001d2d2e0), EmptyDir:(*v1.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*v1.GitRepoVolumeSource)(nil), Secret:(*v1.SecretVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), ISCSI:(*v1.ISCSIVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*v1.PersistentVolumeClaimVolumeSource)(nil), RBD:(*v1.RBDVolumeSource)(nil), FlexVolume:(*v1.FlexVolumeSource)(nil), Cinder:(*v1.CinderVolumeSource)(nil), CephFS:(*v1.CephFSVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), DownwardAPI:(*v1.DownwardAPIVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), AzureFile:(*v1.AzureFileVolumeSource)(nil), ConfigMap:(*v1.ConfigMapVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), Projected:(*v1.ProjectedVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOVolumeSource)(nil), StorageOS:(*v1.StorageOSVolumeSource)(nil), CSI:(*v1.CSIVolumeSource)(nil)}}, v1.Volume{Name:"lib-modules", VolumeSource:v1.VolumeSource{HostPath:(*v1.HostPathVolumeSource)(0xc001d2d300), EmptyDir:(*v1.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*v1.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*v1.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*v1.GitRepoVolumeSource)(nil), Secret:(*v1.SecretVolumeSource)(nil), NFS:(*v1.NFSVolumeSource)(nil), ISCSI:(*v1.ISCSIVolumeSource)(nil), Glusterfs:(*v1.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*v1.PersistentVolumeClaimVolumeSource)(nil), RBD:(*v1.RBDVolumeSource)(nil), FlexVolume:(*v1.FlexVolumeSource)(nil), Cinder:(*v1.CinderVolumeSource)(nil), CephFS:(*v1.CephFSVolumeSource)(nil), Flocker:(*v1.FlockerVolumeSource)(nil), DownwardAPI:(*v1.DownwardAPIVolumeSource)(nil), FC:(*v1.FCVolumeSource)(nil), AzureFile:(*v1.AzureFileVolumeSource)(nil), ConfigMap:(*v1.ConfigMapVolumeSource)(nil), VsphereVolume:(*v1.VsphereVirtualDiskVolumeSource)(nil), Quobyte:(*v1.QuobyteVolumeSource)(nil), AzureDisk:(*v1.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*v1.PhotonPersistentDiskVolumeSource)(nil), Projected:(*v1.ProjectedVolumeSource)(nil), PortworxVolume:(*v1.PortworxVolumeSource)(nil), ScaleIO:(*v1.ScaleIOVolumeSource)(nil), StorageOS:(*v1.StorageOSVolumeSource)(nil), CSI:(*v1.CSIVolumeSource)(nil)}}}, InitContainers:[]v1.Container(nil), Containers:[]v1.Container{v1.Container{Name:"kube-proxy", Image:"k8s.gcr.io/kube-proxy:v1.17.0", Command:[]string{"/usr/local/bin/kube-proxy", "--config=/var/lib/kube-proxy/config.conf", "--hostname-override=$(NODE_NAME)"}, Args:[]string(nil), WorkingDir:"", Ports:[]v1.ContainerPort(nil), EnvFrom:[]v1.EnvFromSource(nil), Env:[]v1.EnvVar{v1.EnvVar{Name:"NODE_NAME", Value:"", ValueFrom:(*v1.EnvVarSource)(0xc001d2d340)}}, Resources:v1.ResourceRequirements{Limits:v1.ResourceList(nil), Requests:v1.ResourceList(nil)}, VolumeMounts:[]v1.VolumeMount{v1.VolumeMount{Name:"kube-proxy", ReadOnly:false, MountPath:"/var/lib/kube-proxy", SubPath:"", MountPropagation:(*v1.MountPropagationMode)(nil), SubPathExpr:""}, v1.VolumeMount{Name:"xtables-lock", ReadOnly:false, MountPath:"/run/xtables.lock", SubPath:"", MountPropagation:(*v1.MountPropagationMode)(nil), SubPathExpr:""}, v1.VolumeMount{Name:"lib-modules", ReadOnly:true, MountPath:"/lib/modules", SubPath:"", MountPropagation:(*v1.MountPropagationMode)(nil), SubPathExpr:""}}, VolumeDevices:[]v1.VolumeDevice(nil), LivenessProbe:(*v1.Probe)(nil), ReadinessProbe:(*v1.Probe)(nil), StartupProbe:(*v1.Probe)(nil), Lifecycle:(*v1.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*v1.SecurityContext)(0xc001c519a0), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]v1.EphemeralContainer(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc001d447d8), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string{"beta.kubernetes.io/os":"linux"}, ServiceAccountName:"kube-proxy", DeprecatedServiceAccount:"kube-proxy", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", HostNetwork:true, HostPID:false, HostIPC:false, ShareProcessNamespace:(*bool)(nil), SecurityContext:(*v1.PodSecurityContext)(0xc001d92000), ImagePullSecrets:[]v1.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*v1.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]v1.Toleration{v1.Toleration{Key:"CriticalAddonsOnly", Operator:"Exists", Value:"", Effect:"", TolerationSeconds:(*int64)(nil)}, v1.Toleration{Key:"", Operator:"Exists", Value:"", Effect:"", TolerationSeconds:(*int64)(nil)}}, HostAliases:[]v1.HostAlias(nil), PriorityClassName:"system-node-critical", Priority:(*int32)(nil), DNSConfig:(*v1.PodDNSConfig)(nil), ReadinessGates:[]v1.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil), PreemptionPolicy:(*v1.PreemptionPolicy)(nil), Overhead:v1.ResourceList(nil), TopologySpreadConstraints:[]v1.TopologySpreadConstraint(nil)}}, UpdateStrategy:v1.DaemonSetUpdateStrategy{Type:"RollingUpdate", RollingUpdate:(*v1.RollingUpdateDaemonSet)(0xc000089268)}, MinReadySeconds:0, RevisionHistoryLimit:(*int32)(0xc001d44818)}, Status:v1.DaemonSetStatus{CurrentNumberScheduled:2, NumberMisscheduled:0, DesiredNumberScheduled:3, NumberReady:1, ObservedGeneration:1, UpdatedNumberScheduled:2, NumberAvailable:1, NumberUnavailable:2, CollisionCount:(*int32)(nil), Conditions:[]v1.DaemonSetCondition(nil)}}: Operation cannot be fulfilled on daemonsets.apps "kube-proxy": the object has been modified; please apply your changes to the latest version and try again
  	220:E0611 16:39:54.142649       1 tokens_controller.go:260] error synchronizing serviceaccount nsm-system/default: secrets "default-token-rh7np" is forbidden: unable to create new content in namespace nsm-system because it is being terminated
  
  
  ./config.kubeconfig/kube-system/etcd-cloudtest-kind-8a1853245b-control-plane/logs.txt
  
  	54:WARNING: 2021/06/11 16:42:33 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
  
  
  ./config.kubeconfig/kube-system/kindnet-gnvzd/logs.txt
  
  	4:I0611 16:36:13.249234       1 main.go:104] Failed to get nodes, retrying after error: Get https://10.96.0.1:443/api/v1/nodes: dial tcp 10.96.0.1:443: i/o timeout
  
  

